version: '3.3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mixtape_db
      POSTGRES_USER: mixtape
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: